### ISSUE TITLE
Message: Service geckodriver unexpectedly exited. Status code was: -11

### ISSUE THREAD

**Issue by No06LuSec** [sundowndev/PhoneInfoga#101]
**After I launch the phoneinfoga.py command -n XXXXXXX, and after it ask format number then an error occurs :**

Would you like to use an additional format for this number ? (y/N) n
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/root/desktop/tool/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/root/desktop/tool/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: -11

**I tried searching through google but the results were not very good. (_I still haven't found a solution to solve this error so far_).**

**Comment by jjamieson1** [comment]
I resolved this by installing the geckodriver.  I am using OSX and brew, and the following installed the dependancy for me:  brew install geckodriver

**Comment by sundowndev** [comment]
Hi, thanks for opening an issue! 👋

It seems you didn't installed geckodriver properly. Did you follow the [install instructions](https://sundowndev.github.io/PhoneInfoga/install/#install-the-geckodriver) ?

>This tool uses Firefox. So you now need to download the [geckodriver](https://github.com/mozilla/geckodriver). This driver is necessary to communicate between your installed browser and Selenium (a package used by PhoneInfoga).

You can verify Firefox and geckdriver are installed correctly by typing `which firefox` and `which geckodriver` in your terminal.

Please answer to these questions : 

1. Are you using Docker ? If no, what is your OS ? (`uname -a` for Linux/MacOS users)
2. What command did you run ?
3. Do you have the latest version of Firefox installed ?
4. Do you have the latest version of geckodriver installed ? (try `geckodriver --version`)

*Note that this tool is not tested under any version of Windows and I don't guarantee it will work properly on it.*

**Comment by sundowndev** [comment]
Closing due to inactivity. Feel free to reopen and add further details!
