### ISSUE TITLE
invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by omtarful** [sundowndev/PhoneInfoga#103]
When I use this commmand:
python3 phoneinfoga.py -n %number% -s footprints

I get the following error: 
Would you like to use an additional format for this number ? (y/N) n
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/mnt/c/Users/omtar/OneDrive/Escritorio/gitApps/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/mnt/c/Users/omtar/OneDrive/Escritorio/gitApps/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/home/omtarful/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/omtarful/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/omtarful/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/omtarful/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/omtarful/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

I got geckodriver's latest version.
I am running it on ubuntu for WSL.

**Comment by sundowndev** [comment]
Did you close the browser before the end of tool execution ?

**Comment by omtarful** [comment]
Thank you, it's working now. I forgot to activate X11. Thanks for your time <3.

**Comment by noiseorigin** [comment]
> Did you close the browser before the end of tool execution ?

I m running it on a win10 kali subsystem and got the same error. And I have the latest Firefox and geckodriver.. Any ideas? I tried restart my system ..
