### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by allelive** [sundowndev/phoneinfoga#1075]
PhoneInfoga Ver. v1.0.0-rc2
Coded by Charon IV
-----------------------------------------------------------------------------------------------------------------
linux mint20
-----------------------------------------------------------------------------------------------------------------
sudo python3 phoneinfoga.py -n +39**********
-----------------------------------------------------------------------------------------------------------------

[!] ---- Fetching informations for 39********** ---- [!]
[*] Running local scan...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f40f1ec95e0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='restcountries.eu', port=443): Max retries exceeded with url: /rest/v2/callingcode/39 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f40f1ec95e0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phoneinfoga.py", line 568, in <module>
    scanNumber(args.number)
  File "phoneinfoga.py", line 521, in scanNumber
    localScan(InputNumber)
  File "phoneinfoga.py", line 238, in localScan
    countryRequest = json.loads(requests.request('GET', 'https://restcountries.eu/rest/v2/callingcode/{}'.format(numberCountryCode.replace('+', ''))).content)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='restcountries.eu', port=443): Max retries exceeded with url: /rest/v2/callingcode/39 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f40f1ec95e0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
-----------------------------------------------------------------------------------------------------------------
![Selezione_465](https://user-images.githubusercontent.com/33356046/174453257-d6169bf8-261c-409e-8bbf-f35e81da73b4.png)
-----------------------------------------------------------------------------------------------------------------
Thanks in advance
-----------------------------------------------------------------------------------------------------------------

**Comment by sundowndev** [comment]
Version 1 is not supported anymore, closing.

**Comment by allelive** [comment]
Ok tanks
