### ISSUE TITLE
phoneInfoga json error

### ISSUE THREAD

**Issue by Annus1212** [sundowndev/PhoneInfoga#108]
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/root/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/root/PhoneInfoga/lib/googlesearch.py", line 29, in search
    return searchApi(req, stop)
  File "/root/PhoneInfoga/lib/googlesearch.py", line 79, in searchApi
    response = r.json()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
AttributeError: module 'simplejson' has no attribute 'loads'

**Comment by sundowndev** [comment]
Hi,

- What command did you run ?
- Did you use python3 ?
- What is your OS ?

**Comment by sundowndev** [comment]
Feel free to add further details about this.

Closing for now.
