### ISSUE TITLE
'geckodriver' executable needs to be in PATH

### ISSUE THREAD

**Issue by snoel-max** [sundowndev/PhoneInfoga#110]
i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/root/PhoneInfoga/sundowndev-PhoneInfoga-74baad0/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/root/PhoneInfoga/sundowndev-PhoneInfoga-74baad0/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by sundowndev** [comment]
Did you install Geckodriver properly ?
Do you have Firefox installed ?

If yes to both,
- What is your OS ? If Linux see https://github.com/sundowndev/PhoneInfoga/issues/84#issuecomment-508943051
- Python version ?

**Comment by snoel-max** [comment]
It's perfect, couldn't ask for more :+1:  Thanks and sorry for the silly mistake .
