### ISSUE TITLE
Geckodriver: Failed to decode response from marionette

### ISSUE THREAD

**Issue by LaurDana** [sundowndev/PhoneInfoga#113]

**Comment by LaurDana** [comment]
Hello, 

It's my first post here and please note that I am not a tech guy. I am just an average Linux user.
I installed PhoneInfoga and the geckodriver. I think I succeded, but I got these messages about failing to connect to the "marionette".
Can you please advise what I did wrong? Because for all the searches that the PhoneInfoga does I receive this message:  
"Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection"



![Screenshot_2019-08-24_01-31-22](https://user-images.githubusercontent.com/54456841/63627461-7ff43d00-c610-11e9-931c-e3d2ca4260e2.png)



[laura@laura PhoneInfoga]$ python3 phoneinfoga.py -n "+4072XXXXXXX"
    ___ _                       _____        __                   
   / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _ 
  / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
 / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
 \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
                                                      |___/       
 PhoneInfoga Ver. v1.10.9
 Coded by Sundowndev


[!] ---- Fetching informations for 4072XXXXXXX ---- [!]
[*] Running local scan...
[+] International format: +40 72X XXX XXX
[+] Local format: 72XXXXXXX
[+] Country found: Romania (+40)
[+] City/Area: Romania
[+] Carrier: Vodafone
[+] Timezone: Europe/Bucharest
[i] The number is valid and possible.
[*] Running Numverify.com scan...
[+] Number: (+40) 072XXXXXXX
[+] Country: Romania (RO)
[+] Location: 
[+] Carrier: Vodafone Romania SA
[+] Line type: mobile
(!) This is most likely a mobile number, but it can still be a VoIP number.
[*] Running OVH scan...
[*] Running OSINT footprint reconnaissance...
[i] Generating scan URL on 411.com...
[+] Scan URL: https://www.411.com/phone/40-72X-XXX-XXX
Would you like to use an additional format for this number ? (y/N) n
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
(!) You are temporary blacklisted from Google search. Complete the captcha then press ENTER.
>
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Failed to decode response from marionette
[i] Searching for documents... (limit=10)
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] ---- Reputation footprints ----
[i] Searching for reputation report on whosenumber.info...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for phone fraud footprints...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for reputation report on findwhocallsme.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for reputation report on yellowpages.ca...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for reputation report on phonenumbers.ie...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for reputation report on who-calledme.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for reputation report on usphonesearch.net...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for reputation report on whocalled.us...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for reputation report on quinumero.info...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for reputation report on uk.popularphotolook.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Generating URL on scamcallfighters.com...
[+] http://www.scamcallfighters.com/search-phone-4072XXXXXXX.html
Would you like to search for temporary number providers footprints ? (Y/n) y
[i] ---- Temporary number providers footprints ----
[i] Searching for phone number on tempophone.com...
[!] Unable to reach tempophone.com API. Skipping.
[i] Searching for footprints on hs3x.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on receive-sms-now.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on smslisten.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on smsnumbersonline.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on freesmscode.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on catchsms.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on smstibo.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on smsreceiving.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on getfreesmsnumber.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on sellaite.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on receive-sms-online.info...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on receivesmsonline.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on receive-a-sms.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on sms-receive.net...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on receivefreesms.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on receive-sms.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on receivetxt.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on freephonenum.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on freesmsverification.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on receive-sms-online.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on smslive.co...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] ---- Social media footprints ----
[i] Searching for footprints on facebook.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on twitter.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on linkedin.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on instagram.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] ---- Phone books footprints ----
[i] Searching for footprints on numinfo.net...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on sync.me...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on whocallsyou.de...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on pastebin.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on whycall.me...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

[i] Searching for footprints on locatefamily.com...
[!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
Message: Tried to run command without establishing a connection

Would you like to rerun OSINT scan ? (e.g to use a different format) (y/N) n
[i] Scan finished.

**Comment by sundowndev** [comment]
Hi, this is definitely a bug from geckodriver.

- What is your OS ?
- What's your python, geckodriver  & firefox version ?

Note that you must have firefox installed.

**Comment by LaurDana** [comment]
Hi,

**OPERATING SYSTEM**:   ManjaroLinux 18.0.4
    Kernel:           4.19.66-1-MANJARO (x86_64)                                                                                  
    Desktop:          Xfce 4.14        


![Screenshot_2019-08-24_10-35-50](https://user-images.githubusercontent.com/54456841/63634213-e05c9c00-c65b-11e9-84ce-81621a57b19a.png)

![Screenshot_2019-08-24_10-37-07](https://user-images.githubusercontent.com/54456841/63634216-eb173100-c65b-11e9-8db1-73f378bdc2c5.png)

The geckodriver I installed is the latest:
![Screenshot_2019-08-24_10-45-44](https://user-images.githubusercontent.com/54456841/63634280-dedfa380-c65c-11e9-8e54-4dca74598a60.png)


Firefox was installed and it is the main browser I use.

Thanks

**Comment by sundowndev** [comment]
Found several topic in geckodriver repository about this:

- https://github.com/mozilla/geckodriver/issues/1125
- https://github.com/mozilla/geckodriver/issues/690
- https://github.com/mozilla/geckodriver/issues/1559

Also found this topic on stackoverflow that describes exactly the problem: https://stackoverflow.com/questions/49734915/failed-to-decode-response-from-marionette-message-in-python-firefox-headless-s

But cannot find a real working solution at the moment. From various discussions, it seems to be a problem with memory. How much hardware memory do you have ?

**Comment by LaurDana** [comment]
I only have 4GB DDR4 to this machine, but I can upgrade to 12 GB.

Before opening this topic I did some google research myself and I found and read that stackoverflow topic. But as I wrote in the first post I am not a programmer so the discussions in that topic are beyond my knowldge.

If you find any solution for this problem please let me know.

Putting geckodriver in path took me some time. I ran several commands found on your page and also on youtube to succeed to put gecko in path.

I also noticed now that the geckodriver is now in **/usr/bin/** but also in **/usr/local/bin/** in the same time on this machine.
Do you think this could be a problem?

Do you think a fresh reinstall of the PhoneInfoga/selenium/python/geckodriver could fix the problem?

Thanks

**Comment by sundowndev** [comment]
A fresh install of Firefox and Geckodriver could help. If not, it could be a compatibility issue.

>I also noticed that the geckodriver is now in /usr/bin/ but also in /usr/local/bin/ in the same time on this machine. Do you think this could be a problem?

I don't think so.

- What is the output of `which firefox` and `which geckodriver` ?

The solution you mentioned could work, can you try by yourself ? You have to edit the file `lib/googlesearch.py` and replace the following code : 

```
# line 35
browser = webdriver.Firefox()
```

with this, including your Firefox path : 

```
browser = webdriver.Firefox(firefox_binary='/usr/bin/firefox')
```

**Comment by LaurDana** [comment]
- **What is the output of which firefox and which geckodriver ?**

I don't fully understand the question. What do you mean by "output"? 


- **You have to edit the file lib/googlesearch.py**
I found the file and the # line 35
My actual Firefox path is /home/laura/.mozilla/
After the reinstall I think it will be the same. Where do I have to include the Firefox path in the edited # 35 line?



- **A fresh install of Firefox and Geckodriver could help.**

I will reinstall an older version of Firefox as I mentioned above. I am not sure how to do the Geckodriver reinstall. Just delete the gheckodriver file from /usr/bin/ and /usr/local/bin/ is enough? Or do I have to run some command lines?
I read yesterday on a youtube video (I can not find it anymore) related to Geckodriver errors, that the solution provided in that video  only worked if selenium was not installed. Do I have to remove&reinstall selenium too?

Thanks

**Comment by sundowndev** [comment]
Before reinstalling, try what I mentioned.

>What do you mean by "output"?

I mean, type the command in your command line and tell me what happens.
So type these commands in your terminal : 
1. `which geckodriver`
2. `which firefox`

Tell me what is the output, then edit the file **lib/googlesearch.py** which is in the PhoneInfoga folder. And replace this : 

```
browser = webdriver.Firefox()
```

By this : 

```
browser = webdriver.Firefox(firefox_binary='/home/laura/.mozilla/firefox')
```

(assuming `/home/laura/.mozilla/firefox` is actually your firefox path)

**Comment by LaurDana** [comment]
[laura@laura ~]$ which geckodriver
/usr/local/bin/geckodriver
[laura@laura ~]$ which firefox
/usr/bin/firefox

**Comment by sundowndev** [comment]
Ok, then you have to replace by

```
browser = webdriver.Firefox(firefox_binary=' /usr/bin/firefox')
```

But this is actually the default path so I don't think this will change anything. This is still worth the try.

**Comment by LaurDana** [comment]
I already found the file and edited it.
Now I ran PhoneInfoga to see if the problem still exists?

![Screenshot_2019-08-24_18-13-12](https://user-images.githubusercontent.com/54456841/63639389-1c632180-c69b-11e9-9585-4c5ce0f097ea.png)

**Comment by sundowndev** [comment]
Wrong path. Use `/usr/bin/firefox`. Then you can run the tool again.

**Comment by LaurDana** [comment]
Would you like to use an additional format for this number ? (y/N) n
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/home/laura/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/home/laura/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox(firefox_binary='/home/laura/.mozilla/firefox')
  File "/home/laura/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/laura/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/laura/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/laura/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/laura/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities


I will change the path you mentioned above and I will post the output.

**Comment by LaurDana** [comment]
I change the path as you instructed and I ran the tool again.
The problem is still there.

> 
> 
> [!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
> Message: Failed to decode response from marionette
> 
> [i] Searching for documents... (limit=10)
> [!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
> Message: Tried to run command without establishing a connection
> 
> [i] ---- Reputation footprints ----
> [i] Searching for reputation report on whosenumber.info...
> [!] Request failed. Please retry or open an issue on https://github.com/sundowndev/PhoneInfoga.
> Message: Tried to run command without establishing a connection


I will reinstall the Firefox with an older version, v66 worked for that user.
Please advise about the geckodriver reinstall. Just delete the Geckodriver file from /usr/bin/ and /usr/local/bin/ is enough? Or do I have to run some command lines?

**Comment by sundowndev** [comment]
>Just delete the Geckodriver file from /usr/bin/ and /usr/local/bin/ is enough? Or do I have to run some command lines?

Deleting geckodriver executable in `/usr/bin/` and `/usr/local/bin/` is enough.

**Comment by LaurDana** [comment]
Hi,

I tried to install v66 of Firefox folowing the instructions from the Mozilla website for installing outside of a package manager. [https://support.mozilla.org/en-US/kb/install-firefox-linux](url)
I don't know if this is the only way to install an older version of Firefox.
Unfortunately I succeded to launch Firefox only from the terminal using this command `~/firefox/firefox`.

![Screenshot_2019-08-25_19-34-00](https://user-images.githubusercontent.com/54456841/63653364-6d931400-c774-11e9-8a11-bcfa59c7204d.png)


When I tried to check Firefox with the command `which firefox` the output was 

> [laura@laura ~]$ which firefox
> which: no firefox in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)

I ran the tool again and the output was:

> Would you like to use an additional format for this number ? (y/N) n
> [i] ---- Web pages footprints ----
> [i] Searching for footprints on web pages... (limit=10)
> Traceback (most recent call last):
>   File "phoneinfoga.py", line 95, in <module>
>     main()
>   File "phoneinfoga.py", line 71, in main
>     scanNumber(args.number)
>   File "phoneinfoga.py", line 38, in scanNumber
>     osintScan(number)
>   File "/home/laura/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
>     for result in search(req, stop=10):
>   File "/home/laura/PhoneInfoga/lib/googlesearch.py", line 35, in search
>     browser = webdriver.Firefox(firefox_binary='/usr/bin/firefox')
>   File "/home/laura/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
>     keep_alive=True)
>   File "/home/laura/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "/home/laura/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "/home/laura/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/home/laura/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
> 


Geckodriver was reinstalled ok

> [laura@laura ~]$ which geckodriver
> /usr/bin/geckodriver

**Comment by sundowndev** [comment]
>[laura@laura ~]$ which firefox
which: no firefox in (/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)

This means firefox is not installed (properly). And so, PhoneInfoga will not run as it should.

> Unfortunately I succeded to launch Firefox only from the terminal using this command ~/firefox/firefox.

This means firefox executable is located at `/home/laura/firefox/firefox`. You should try to move it to a bin path like this : 

```
cp ~/firefox/firefox /usr/local/bin/firefox
```

Then retry the command `which firefox`, it should output `/usr/local/bin/firefox`.

**Comment by LaurDana** [comment]
That command did not work. I ran it as a root also and the output is the same.

> [laura@laura ~]$ cp ~/firefox/firefox /usr/local/bin/firefox
> cp: cannot create regular file '/usr/local/bin/firefox': Permission denied
> [laura@laura ~]$ sudo su
> [sudo] password for laura: 
> [laura laura]# cp ~/firefox/firefox /usr/local/bin/firefox
> cp: cannot stat '/root/firefox/firefox': No such file or directory

The v66 Mozilla archive is downloaded on this path on my machine `/home/laura/`. The `firefox` folder including the `firefox` executable is on the same path. I installed Firefox folowing with these instructions from Mozilla website:

![Screenshot_2019-08-26_00-02-24](https://user-images.githubusercontent.com/54456841/63655799-76e0a880-c795-11e9-87a3-92d99722be70.png)
 
Firefox is working but I can only launch it from terminal and also can't find it in installed packages in pamac.

**Comment by darknodi** [comment]
@sundowndev I have followed ( MESSAGE ERROR FROM BASH UBUNTU ) God thankest you. 

[i] Footprint reconnaissance for +3550692021500
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 37, in scanNumber
    recon.scan(number)
  File "/home/cabox/workspace/PhoneInfoga/scanners/recon.py", line 88, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/home/cabox/workspace/PhoneInfoga/lib/googlesearch.py", line 28, in search
    if google_api_key and google_cx_id:
NameError: name 'google_api_key' is not defined

**Comment by sundowndev** [comment]
@darknodi 1. This is off-topic
2. You didn't follow the install instructions in the docs
3. Stop spamming issues or I'm blocking you

**Comment by sundowndev** [comment]
@LaurDana 
>sudo cp ~/firefox/firefox /usr/local/bin/firefox

Well, since you logged as root (not recommanded), what you actually typed is `sudo cp /home/root/firefox/firefox /usr/local/bin/firefox` but what you wanted is `sudo cp /home/laura/firefox/firefox /usr/local/bin/firefox`.

Because in UNIX systems, `~/` means `/home/${USER}`.
So try with this : `sudo cp /home/laura/firefox/firefox /usr/local/bin/firefox`

Don't type `sudo su`, just `sudo {command}`

**Comment by LaurDana** [comment]
I ran the previous command you posted `cp ~/firefox/firefox /usr/local/bin/firefox` first as normal user and after that as root. Both failed.

Now I ran `sudo cp /home/laura/firefox/firefox /usr/local/bin/firefox` as you instructed but Firefox still doesn' launch and still doesn't appear in Pamac.

![Screenshot_2019-08-26_20-08-25](https://user-images.githubusercontent.com/54456841/63709418-85839a00-c83f-11e9-9150-78303dd167b9.png)

But I can launch it from the terminal with this command `~/firefox/firefox`.
After I closed Firefox I got this message on terminal. It say something about `gecko`. I am on Chromium browser now.

![Screenshot_2019-08-26_20-19-51](https://user-images.githubusercontent.com/54456841/63709544-cda2bc80-c83f-11e9-8992-060391641e5d.png)

**Comment by sundowndev** [comment]
>Now I ran sudo cp /home/laura/firefox/firefox /usr/local/bin/firefox as you instructed but Firefox still doesn' launch and still doesn't appear in Pamac.

This command will simply link the firefox executable in your PATH. Which means you can now launch firefox just by typing `firefox` in the terminal. This is needed for PhoneInfoga to launch firefox.

**Comment by LaurDana** [comment]
[laura@laura ~]$ firefox
Exec failed with error: No such file or directory

**Comment by sundowndev** [comment]
Again, what's the output of `which firefox` ?

If you cannot get this working, consider using Docker : https://sundowndev.github.io/PhoneInfoga/install/#docker-compose

>Docker is a computer program that performs operating-system-level virtualization also known as containerization. 

Which will allows you to run PhoneInfoga, Firefox and everything else in a virtual environment. You'll need docker and docker-compose.

**Comment by LaurDana** [comment]
**what's the output of which firefox ?**
[laura@laura ~]$ which firefox
/usr/local/bin/firefox




 **consider using Docker**
Thanks for the advice. I'll read on how to use it and then try it.

**Comment by LaurDana** [comment]
Hi,
Do you think that if python is installed in another path as the Firefox is, could be the reason that the tool doesn't work?
Since I've learned from you the command `which`, I checked all the paths for the required software for PhoneInfoga.

> [laura@laura ~]$ which python
> /usr/bin/python
> [laura@laura ~]$ which firefox
> /usr/local/bin/firefox

So the python is in /usr/bin but the Firefox is in /usr/**local**/bin
Coukd this be the problem?

**Comment by progamandoconro** [comment]
Please try it. I will try to run the Dockerfile again today, yesterday a
managed to solve the first problem about the gecko. I will share if I have
success.

**Comment by LaurDana** [comment]
@progamandoconro I don't understand what exactly to try?
If you mean to move python to /usr/local/bin to be in the same path as Firefox, I will need some help to do this. As I said in my first post I am just an average Linux user.
Please note that I installed python using this command:
`python3 -m pip install -r requirements.txt --user`

Thanks

**Comment by sundowndev** [comment]
@LaurDana He's talking about using Docker.

**Comment by LaurDana** [comment]
I installed docker, pulled the repository as you instructed and then tried to run the tool.
The output was: bash: phoneinfoga.py: command not found

```
[laura@laura ~]$ docker run --rm -it sundowndev/phoneinfoga --help
usage: phoneinfoga.py -n <number> [options]

Advanced information gathering tool for phone numbers
(https://github.com/sundowndev/PhoneInfoga) version v1.10.9

optional arguments:
  -h, --help            show this help message and exit
  -n number, --number number
                        The phone number to scan (E164 or international
                        format)
  -i input_file, --input input_file
                        Phone number list to scan (one per line)
  -o output_file, --output output_file
                        Output to save scan results
  -s scanner, --scanner scanner
                        The scanner to use
  --recon               Launch custom format reconnaissance
  --no-ansi             Disable colored output
  -v, --version         Show tool version
[laura@laura ~]$ phoneinfoga.py -n +407XXXXXXXX
bash: phoneinfoga.py: command not found
```
Did I do something wrong?


The docker seems to be installed properly.

```
laura@laura ~]$ docker version
Client:
 Version:           19.03.1-ce
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        74b1e89e8a
 Built:             Fri Aug 16 14:00:42 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.1-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       74b1e89e8a
  Built:            Fri Aug 16 13:58:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.8.m
  GitCommit:        a4bc1d432a2c33aa2eed37f338dceabb93641310.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by sundowndev** [comment]
>Did I do something wrong?

@LaurDana Yes. Since you are running the tool in Docker, you have to use `docker run --rm -it sundowndev/phoneinfoga` as executable, not `phoneinfoga.py`.

So the command should be : `docker run --rm -it sundowndev/phoneinfoga -n +407XXXXXXXX`

**Comment by LaurDana** [comment]
Of course. I should have seen that in the previous command I used, copied from your installation documentation.

Now I ran the command properly but I still get an error message:

```
[laura@laura ~]$ docker run --rm -it sundowndev/phoneinfoga -n +4072xxxxxxx
    ___ _                       _____        __                   
   / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _ 
  / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
 / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
 \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
                                                      |___/       
 PhoneInfoga Ver. v1.10.9
 Coded by Sundowndev


[!] ---- Fetching informations for 4072xxxxxxx ---- [!]
[*] Running local scan...
[+] International format: +40 72x xxx xxx
[+] Local format: 726xxxxxxx
[+] Country found: Romania (+40)
[+] City/Area: Romania
[+] Carrier: Vodafone
[+] Timezone: Europe/Bucharest
[i] The number is valid and possible.
[*] Running Numverify.com scan...
[+] Number: (+40) 0726xxxxxxx
[+] Country: Romania (RO)
[+] Location: 
[+] Carrier: Vodafone Romania SA
[+] Line type: mobile
(!) This is most likely a mobile number, but it can still be a VoIP number.
[*] Running OVH scan...
[*] Running OSINT footprint reconnaissance...
[i] Generating scan URL on 411.com...
[+] Scan URL: https://www.411.com/phone/40-72x-xxx-xxx
Would you like to use an additional format for this number ? (y/N) n
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "/usr/local/lib/pyenv/versions/3.6.9/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/local/lib/pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/opt/phoneinfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/opt/phoneinfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/pyenv/versions/3.6.9/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/pyenv/versions/3.6.9/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
``` 

Please note that I didn't used docker-compose file because it's beyond my skills.

**Comment by sundowndev** [comment]
You have to run geckodriver with docker-compose (following this guide: https://sundowndev.github.io/PhoneInfoga/install/#from-the-source-code). Did you ?

To verify, what is the output of `docker ps` ?

**Comment by LaurDana** [comment]
[laura@laura ~]$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[laura@laura ~]$


I didn't used docker-compose because I didn't know where to find that source code you were talking about in the guide, to download it.

I don't use MacOS. I use Linux Manjaro.

**Comment by sundowndev** [comment]
>I didn't used docker-compose because I didn't know where to find that source code you were talking about in the guide, to download it.

The source code is the actual code in this GitHub repository. You just have to pull it and run docker-compose inside the folder.

>I don't use MacOS. I use Linux Manjaro.

Ok never mind. There's also a lot of VNC clients on Linux.

**Comment by sundowndev** [comment]
Closing due to inactivity. Feel free to reopen and add further details!

**Comment by LaurDana** [comment]
Hi

I installed Kali Linux in VirtualBox on the same machine where I have Manjaro as host OS. The tool works fine on Kali.
No hardware or software changes were made on the machine configuration since opening this thread.
On host OS - Manjaro Linux, the tool still doesn't work.

**Comment by sundowndev** [comment]
Hi @LaurDana, thank you for updating this issue. I'm glad you finally made it work. This is probably an issue with Manjaro and Geckodriver. Feel free to reopen and give further details about this bug :)
