### ISSUE TITLE
 Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by kstepanyan111** [sundowndev/PhoneInfoga#124]
**Describe the bug**
Not sure if this a bug !
After running command 
` python3 phoneinfoga.py -n +number`
I got 
```
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/root/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/root/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```
Server 
Centos 7 

```
 geckodriver --version
geckodriver 0.25.0 (bdb64cf16b68 2019-09-10)

The source code of this program is available from
testing/geckodriver in https://hg.mozilla.org/mozilla-central.

This program is subject to the terms of the Mozilla Public License 2.0.
You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.
```
```
 python --version
Python 3.6.3
```
Did I understand it right that program can not work on plain server as it tries to open selenium ?
**Thanks for amazing job !**

**Comment by sundowndev** [comment]
The error comes from selenium and tell you that it cannot reach geckodriver.

- Do you have Firefox installed ?
- What is the output of `which geckodriver` ?

**Comment by kstepanyan111** [comment]
Yep it is a plain server on a remote machine .
```
which geckodriver
/usr/bin/geckodriver
```
There is no way to move on without solving the captcha ?
somehow make tool to skip this part with firefox ?

**Comment by sundowndev** [comment]
Yes you can skip the footprinting part by not using `--recon` and `-s footprints`. So use `-n +number -s numverify` or `-n +number -s ovh`

**Comment by progamandoconro** [comment]
Nice !

**Comment by kstepanyan111** [comment]
:) with `-s ovh` flag I got almost nothing 
which I presume is fine 
at least no error

**Comment by sundowndev** [comment]
>OVH is, besides being a web and cloud hosting company, a telecom provider with several VoIP numbers in Europe. Thanks to their free API, we are able to tell if a number is owned by OVH Telecom or not.

https://sundowndev.github.io/PhoneInfoga/usage/#available-scanners

**Comment by sundowndev** [comment]
Also, if you have a Google API key, Selenium will not be used and request will run on a plain server. Read https://sundowndev.github.io/PhoneInfoga/googlesearch/#using-google-api-key

Please close if solved.

**Comment by kstepanyan111** [comment]
Thanks for help
