### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'geckodriver.log'

### ISSUE THREAD

**Issue by Shiftylab** [sundowndev/PhoneInfoga#127]
Receiving an error with geckodriver.log in Kali. Only happens when using --recon or doing a normal scan and then looking for more information.

> Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 37, in scanNumber
    recon.scan(number)
  File "/home/Blind/PhoneInfoga/scanners/recon.py", line 88, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/home/Blind/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/home/Blind/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 163, in __init__
    log_path=service_log_path)
  File "/home/Blind/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/service.py", line 44, in __init__
    log_file = open(log_path, "a+") if log_path is not None and log_path != "" else None
PermissionError: [Errno 13] Permission denied: 'geckodriver.log'

**Comment by sundowndev** [comment]
Do you have the latest version of Firefox and Geckodriver ?
Please try `pip install --upgrade selenium`. What's the output of `which geckodriver` ?

**Comment by Shiftylab** [comment]
I ended up wiping Windows and running Parrot as my host OS, and I don't have this issue anymore. Thank you though.
