### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by mignal104** [sundowndev/PhoneInfoga#128]
Im new to all this ethical hacking and coding, but i have an issue with the soft. and btw its my first post, so i dont know if thats right what im doing now. never mind. lets go.

so i entered the number and its working and searching info about that number untill it starts "Searching for footprints on web pages"

is there any way to fix that automatic using some kind of commands or i need to fix this manually. if manually please give me some tips how to to that. 

im using python3.7.4 on linux OS. 

"Would you like to use an additional format for this number ? (y/N) n
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/root/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/root/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. "

**Comment by sundowndev** [comment]
You need to install geckodriver, which will allows you to query Google and solve captcha. If you don't want to, just don't use `--recon` and the `footprints` scanner options. Since "all" is the default value for scanner, footprints is also triggered.

Hope this is clear. Read documentation at https://sundowndev.github.io/PhoneInfoga/install/

**Comment by mignal104** [comment]
Yes, i installed geckodriver and its working now. but i have issue which i will fix it by myself its about google blacklist, because im using vm through the whonix. But thank you  for fix !
