### ISSUE TITLE
phoneinfoga 2.10.7 build issue

### ISSUE THREAD

**Issue by chenrui333** [sundowndev/phoneinfoga#1297]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
==> yarn build

-  Building for production...
Starting type checking service...
Using 1 worker with 2048MB memory limit
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/webpack/lib/NormalModule.js:503:5
    at /tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/webpack/lib/NormalModule.js:358:12
    at /tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/loader-runner/lib/LoaderRunner.js:[130](https://github.com/Homebrew/homebrew-core/actions/runs/5417548217/jobs/9848685934?pr=135313#step:4:134):11)
    at iterateNormalLoaders (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/loader-runner/lib/LoaderRunner.js:114
			throw e;
			^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/webpack/lib/util/createHash.js:[135](https://github.com/Homebrew/homebrew-core/actions/runs/5417548217/jobs/9848685934?pr=135313#step:4:139):53)
    at NormalModule._initBuildHash (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/webpack/lib/NormalModule.js:503:5
    at /tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/webpack/lib/NormalModule.js:358:12
    at /tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/cache-loader/dist/index.js:[147](https://github.com/Homebrew/homebrew-core/actions/runs/5417548217/jobs/9848685934?pr=135313#step:4:151):7
    at /tmp/phoneinfoga-20230629-6305-1ycs8y3/phoneinfoga-2.10.7/web/client/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:188:23) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.3.1
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5417548217/jobs/9848685934
relates to Homebrew/homebrew-core#135313

**Comment by chenrui333** [comment]
The build patch works for me, gonna close this issue now. Thanks @sundowndev!
