### ISSUE TITLE
No module named 'config'

### ISSUE THREAD

**Issue by manishpurohit99** [sundowndev/PhoneInfoga#130]
Getting this error... 

There is only one config file named config.example.py throught the package.
Is config an pre-defined Module?

Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/Desktop/PhoneInfoga-master/lib/googlesearch.py", line 15, in <module>
    from config.example import *
ModuleNotFoundError: No module named 'config'

**Comment by sundowndev** [comment]
Duplicate of #70
