### ISSUE TITLE
Formatting error

### ISSUE THREAD

**Issue by RCCRAFT1** [sundowndev/PhoneInfoga#135]
I tried with a county code and this is what happened 
`python3 phoneinfoga.py -n  18883620666 
    ___ _                       _____        __                   
   / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _ 
  / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
 / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
 \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
                                                      |___/       
 PhoneInfoga Ver. v1.10.9
 Coded by Sundowndev

[!] ---- Fetching informations for 18883620666 ---- [!]
[*] Running local scan...
[+] International format: +1 888-362-0666
[+] Local format: 8883620666
[+] Country found:  (+1)
[+] City/Area: 
[+] Carrier: 
[+] Timezone: America/Adak
[+] Timezone: America/Anchorage
[+] Timezone: America/Anguilla
[+] Timezone: America/Antigua
[+] Timezone: America/Barbados
[+] Timezone: America/Boise
[+] Timezone: America/Cayman
[+] Timezone: America/Chicago
[+] Timezone: America/Denver
[+] Timezone: America/Dominica
[+] Timezone: America/Edmonton
[+] Timezone: America/Fort_Nelson
[+] Timezone: America/Grand_Turk
[+] Timezone: America/Grenada
[+] Timezone: America/Halifax
[+] Timezone: America/Jamaica
[+] Timezone: America/Juneau
[+] Timezone: America/Los_Angeles
[+] Timezone: America/Lower_Princes
[+] Timezone: America/Montserrat
[+] Timezone: America/Nassau
[+] Timezone: America/New_York
[+] Timezone: America/North_Dakota/Center
[+] Timezone: America/Phoenix
[+] Timezone: America/Port_of_Spain
[+] Timezone: America/Puerto_Rico
[+] Timezone: America/Santo_Domingo
[+] Timezone: America/St_Johns
[+] Timezone: America/St_Kitts
[+] Timezone: America/St_Lucia
[+] Timezone: America/St_Thomas
[+] Timezone: America/St_Vincent
[+] Timezone: America/Toronto
[+] Timezone: America/Tortola
[+] Timezone: America/Vancouver
[+] Timezone: America/Winnipeg
[+] Timezone: Atlantic/Bermuda
[+] Timezone: Pacific/Guam
[+] Timezone: Pacific/Honolulu
[+] Timezone: Pacific/Pago_Pago
[+] Timezone: Pacific/Saipan
[i] The number is valid and possible.
[*] Running Numverify.com scan...
[+] Number: (+1) 8883620666
[+] Country: United States of America (US)
[+] Location: 
[+] Carrier: 
[+] Line type: toll_free
[*] Running OVH scan...
[*] Running OSINT footprint reconnaissance...
[i] Generating scan URL on 411.com...
[+] Scan URL: https://www.411.com/phone/1-888-362-0666
Would you like to use an additional format for this number ? (y/N) y
[i] We recommand: +1 888-362-0666 or 888-362-0666
Custom format: +1 888-362-0666
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/root/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/root/PhoneInfoga/lib/googlesearch.py", line 28, in search
    if google_api_key and google_cx_id:
NameError: name 'google_api_key' is not defined
root@kali:~/PhoneInfoga# 
`

**Comment by sundowndev** [comment]
It means you didn't create the config file. Please read the documentation : https://sundowndev.github.io/PhoneInfoga/install/#create-the-config-file.
