### ISSUE TITLE
Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by jhefetz** [sundowndev/PhoneInfoga#140]
> Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/root/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/root/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Please advise

**Comment by jhefetz** [comment]
Looking now, it is either the same or nearly the same as #133

**Comment by sundowndev** [comment]
Hi, thanks for opening an issue! 👋

It seems you didn't installed geckodriver properly. See [this comment on stackoverflow](https://stackoverflow.com/a/40437690).

1. Are you using Docker ?
2. What command did you run ?
3. What is your OS ? (`uname -a` for Linux/MacOS users)
4. Do you have the latest version of Firefox installed ?
5. Do you have the latest version of geckodriver installed ? (try `geckodriver --version`)

Finally, did you follow the [install instructions](https://sundowndev.github.io/PhoneInfoga/install/#install-the-geckodriver) ?

*Note that this tool is not tested under any version of Windows and I don't guarantee it will work.*

**Comment by sundowndev** [comment]
Closing due to inactivity. Feel free to reopen and add further details!
