### ISSUE TITLE
Issue while adding an additionnal format

### ISSUE THREAD

**Issue by unguest** [sundowndev/PhoneInfoga#141]
Everytime I try to add an additionnal format after scanning a phone number, this error's raising...

Traceback (most recent call last):
  File "/home/arthur/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/home/arthur/Documents/Toolbox/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/home/arthur/Documents/Toolbox/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/home/arthur/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/arthur/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by sundowndev** [comment]
Hi, thanks for opening an issue! 👋

It seems you didn't installed geckodriver properly. See [this comment on stackoverflow](https://stackoverflow.com/a/40437690).

1. Are you using Docker ?
2. What command did you run ?
3. What is your OS ? (`uname -a` for Linux/MacOS users)
4. Do you have the latest version of Firefox installed ?
5. Do you have the latest version of geckodriver installed ? (try `geckodriver --version`)

Finally, did you follow the [install instructions](https://sundowndev.github.io/PhoneInfoga/install/#install-the-geckodriver) ?

*Note that this tool is not tested under any version of Windows and I don't guarantee it will work.*

**Comment by unguest** [comment]
Yes I used docker and I'm running Ubuntu 18.04 LTS with lastest Fireofx & geckodriver installed.
I installed it via the installation page.

**Comment by sundowndev** [comment]
When using Docker, you don't need to have Firefox and Geckodriver installed on your host machine. Simply use docker-compose as [mentioned here](https://sundowndev.github.io/PhoneInfoga/install/#from-the-source-code) (after cloning the repository). Then install a VNC client on your host machine to access Firefox through Docker. As [explained here](https://sundowndev.github.io/PhoneInfoga/googlesearch/#using-docker).

**Comment by sundowndev** [comment]
Closing due to inactivity. Feel free to reopen and add further details!
