### ISSUE TITLE
not starting

### ISSUE THREAD

**Issue by lebanesgamer** [sundowndev/PhoneInfoga#142]
this is what i get after typing : python3 phoneinfago.py -v

Traceback (most recent call last):
  File "phoneinfoga.py", line 14, in <module>
    from lib.output import *
  File "/root/PhoneInfoga/lib/output.py", line 10, in <module>
    from lib.colors import *
  File "/root/PhoneInfoga/lib/colors.py", line 9, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'

**Comment by sundowndev** [comment]
You have to install dependencies. Read https://sundowndev.github.io/PhoneInfoga/install/

**Comment by lebanesgamer** [comment]
Thanks
