### ISSUE TITLE
advice me fix this error

### ISSUE THREAD

**Issue by secubin** [sundowndev/PhoneInfoga#1427]
python phoneinfoga.py -n +91xxxxxxxxxxx
Traceback (most recent call last):
  File "/home/kali/DTools/PhoneInfoga/phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/home/kali/DTools/PhoneInfoga/lib/googlesearch.py", line 15, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'

**Comment by sundowndev** [comment]
You are using version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.
