### ISSUE TITLE
An error occured while parsing

### ISSUE THREAD

**Issue by mk-omg** [sundowndev/PhoneInfoga#144]
[*] Running local scan...
[!] Error: an error occured parsing 7978273054. Skipping.
$

**Comment by sundowndev** [comment]
Hi,

1. What is the country code of the number ?
2. Which command did you run ?

Please provide the phone number, the exact input you used. Censor the last 3 digits.
Example : `python3 phoneinfoga.py -n "+1 512-444-000"`.

**Comment by D4201** [comment]
how could this happen ? 
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/root/PhoneInfoga/lib/googlesearch.py", line 15, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'

**Comment by susheel264** [comment]
What about Indian number?

**Comment by sundowndev** [comment]
Closing due to inactivity. Feel free to reopen and add further details!
