### ISSUE TITLE
Footprint scan doesn't work

### ISSUE THREAD

**Issue by yousifj129** [sundowndev/PhoneInfoga#1449]
Everytime I try, even with different numbers, this error pops up

**To Reproduce**
sudo python3 phoneinfoga.py -n "some number" -s footprints

**Expected behavior**
I didn't expect an error, maybe it wouldn't find anything, but not an error, OVH works though.

![image](https://github.com/user-attachments/assets/615d23ef-7a56-44f3-bae0-777aed554be4)

 - OS: WSL kali linux - windows 11
 - Version v1.10.9

Error:
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "/home/kali/Downloads/PhoneInfoga/phoneinfoga.py", line 95, in <module>
    main()
  File "/home/kali/Downloads/PhoneInfoga/phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "/home/kali/Downloads/PhoneInfoga/phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/home/kali/Downloads/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Downloads/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

**Comment by sundowndev** [comment]
You are using version 1 which is not supported anymore. Please [read documentation](https://sundowndev.github.io/phoneinfoga/install/) to install version 2.
