### ISSUE TITLE
Message: invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by JohnCarter246** [sundowndev/PhoneInfoga#145]
root@Jacob-C:~/Plocha/Git/PhoneInfoga# python3 phoneinfoga.py -n +420xxxxxxxxx --recon
    ___ _                       _____        __                   
   / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _ 
  / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
 / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
 \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
                                                      |___/       
 PhoneInfoga Ver. v1.10.9
 Coded by Sundowndev

[!] ---- Fetching informations for 420xxxxxxxxx ---- [!]
[*] Running local scan...
[+] International format: +420 xxx xxx xxx
[+] Local format: xxxxxxxxx
[+] Country found: Czechia (+420)
[+] City/Area: Czechia
[+] Carrier: O2
[+] Timezone: Europe/Prague
[i] The number is valid and possible.
[*] Running Numverify.com scan...
[+] Number: (+420) xxxxxxxxx
[+] Country: Czech Republic (CZ)
[+] Location: 
[+] Carrier: O2 Czech Republic a.s.
[+] Line type: mobile
(!) This is most likely a mobile number, but it can still be a VoIP number.
[*] Running OVH scan...
[*] Running custom format reconnaissance...
[i] Footprint reconnaissance for +4200xxxxxxxxx
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 37, in scanNumber
    recon.scan(number)
  File "/home/jacob-carter/Plocha/Git/PhoneInfoga/scanners/recon.py", line 88, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/home/jacob-carter/Plocha/Git/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/home/jacob-carter/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/jacob-carter/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/jacob-carter/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/jacob-carter/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jacob-carter/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

------------------------------------------------------------------------------------------------------------------------------------I try use PhoneInfoga, but I have problem. Can somebody helps me?

**Comment by harrington59802** [comment]
I've had the same issue, with identical output for the error message.

**Comment by spicyboi3750** [comment]
I've had the same issue as well, anybody find a solution?

**Comment by xslendix** [comment]
Anyone?

**Comment by Justin-Lund** [comment]
Also having this issue. On Kali Linux, using GeckoDriver 0.26.0 & Firefox 68.2.0esr

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).
