### ISSUE TITLE
Errors after adding additional format

### ISSUE THREAD

**Issue by sbobola44** [sundowndev/PhoneInfoga#146]
After I put a number in and it asks for a second format and i input a second format I get this error.

The terminal reads"

[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/root/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/root/PhoneInfoga/lib/googlesearch.py", line 28, in search
    if google_api_key and google_cx_id:
NameError: name 'google_api_key' is not defined
"

Any idea how to fix this?

**Comment by sundowndev** [comment]
You have to create the config file. Please read the documentation at https://sundowndev.github.io/PhoneInfoga/install/#create-the-config-file.

**Comment by ZetterSploit** [comment]
Define your api Key. Check documentation.
