### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by stormtrooper298** [sundowndev/PhoneInfoga#153]
**Describe the bug**

Using command python3 phoneinfoga.py -n 1614532xxxx

Results in ::
(After fixing a few other issues, leading up to this)

Would you like to use an additional format for this number ? (y/N) N
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/home/debian-nas/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/home/debian-nas/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

**To Reproduce**
Using command python3 phoneinfoga.py -n 1614532xxxx

**Expected behavior**
To get the results from the search. 

**Screenshots (optional)**
N/A

**Desktop (please complete the following information):**
 - OS: Debian 9 
 - Python 3.5.3

**Additional context**
N/A

**Comment by sundowndev** [comment]
Hi, can you please give me the output of `which geckodriver` and `which firefox` ?
You can also try setting up your Firefox path in the config file (you may have to update the tool).

**Comment by RizzoRavier** [comment]
hey
im new to most of the linux command line and i seem to be having a problem
[i] Footprint reconnaissance for 5873201274
Traceback (most recent call last):
  File "phoneinfoga.py", line 101, in <module>
    main()
  File "phoneinfoga.py", line 77, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 39, in scanNumber
    recon.scan(number)
  File "/home/pi/PhoneInfoga/scanners/recon.py", line 104, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/home/pi/PhoneInfoga/lib/googlesearch.py", line 49, in search
    browser = getFirefoxBrowser()
  File "/home/pi/PhoneInfoga/lib/googlesearch.py", line 35, in getFirefoxBrowser
    return webdriver.Firefox(firefox_binary=binary)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'geckodriver'


My firefox path is listed in the config file

**Comment by RizzoRavier** [comment]
i also seem to be having this problem or more-so a version of this problem 

[i] Footprint reconnaissance for (**********)
Traceback (most recent call last):
  File "phoneinfoga.py", line 101, in <module>
    main()
  File "phoneinfoga.py", line 77, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 39, in scanNumber
    recon.scan(number)
  File "/home/pi/PhoneInfoga/scanners/recon.py", line 104, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/home/pi/PhoneInfoga/lib/googlesearch.py", line 49, in search
    browser = getFirefoxBrowser()
  File "/home/pi/PhoneInfoga/lib/googlesearch.py", line 35, in getFirefoxBrowser
    return webdriver.Firefox(firefox_binary=binary)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'geckodriver'

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).
