### ISSUE TITLE
NameError: name 'google_api_key' is not defined

### ISSUE THREAD

**Issue by xTheMIST** [sundowndev/PhoneInfoga#157]
Would you like to use an additional format for this number ? (y/N) n
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/root/Downloads/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/root/Downloads/PhoneInfoga/lib/googlesearch.py", line 28, in search
    if google_api_key and google_cx_id:
NameError: name 'google_api_key' is not defined

**Comment by sundowndev** [comment]
It seems, you didn't install the project properly. Did you [read documentation](https://sundowndev.github.io/PhoneInfoga/install/) ?

**Comment by sundowndev** [comment]
Closing due to inactivity. Feel free to reopen and add further details.
