### ISSUE TITLE
Exec format error: 'geckodriver'

### ISSUE THREAD

**Issue by ggggggggggg12** [sundowndev/PhoneInfoga#159]
Would you like to use an additional format for this number ? (y/N) n
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/home/pi/PhoneInfoga/sundowndev-PhoneInfoga-74baad0/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/home/pi/PhoneInfoga/sundowndev-PhoneInfoga-74baad0/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'geckodriver'

**Comment by sundowndev** [comment]
Hi, thanks for opening an issue! 👋

It seems you didn't installed geckodriver properly. Did you follow the [install instructions](https://sundowndev.github.io/PhoneInfoga/install/#install-the-geckodriver) ?

>This tool uses Firefox. So you now need to download the [geckodriver](https://github.com/mozilla/geckodriver). This driver is necessary to communicate between your installed browser and Selenium (a package used by PhoneInfoga).

You can verify Firefox and geckodriver are correctly installed by typing `which firefox` and `which geckodriver` in your terminal.

Please consider answering to these questions : 

1. Are you using Docker ? If no, what is your OS ? (`uname -a` for Linux/MacOS users)
2. What command did you run ?
3. Do you have the latest version of Firefox installed ?
4. Do you have the latest version of geckodriver installed ? (try `geckodriver --version`)

*Note that this tool is not tested under any version of Windows and I don't guarantee it will properly work on it.*

**Comment by sundowndev** [comment]
Closing due to inactivity. Feel free to reopen and add further details!

**Comment by thewasta** [comment]
Hey! I have the same error.
1. Yes, Im using Docker 19.03.5
2. `docker pull sundowndev/phoneinfoga:latest` and `docker run --rm -it sundowndev/phoneinfoga -n ` (and a number phone)
