### ISSUE TITLE
help me to fix this please

### ISSUE THREAD

**Issue by azamet90** [sundowndev/PhoneInfoga#164]
**Describe the bug**

**To Reproduce**
└──╼ $sudo python3 phoneinfoga.py -n +00000000000

**Expected behavior**
it should start searching the phone number :D 

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/44042178/70543192-f9567200-1ba4-11ea-9f9d-4eb7bcc7abcb.png)

**Desktop (please complete the following information):**
 - OS: Kali Linux latest
 - Python 2.7.17 and Python 3.7.5

**Additional context**
```
Traceback (most recent call last):
File "phoneinfoga.py", line 95, in
main()
File "phoneinfoga.py", line 71, in main
scanNumber(args.number)
File "phoneinfoga.py", line 37, in scanNumber
recon.scan(number)
File "/root/PhoneInfoga/scanners/recon.py", line 88, in scan
for result in search('"%s"' % (format), stop=5):
File "/root/PhoneInfoga/lib/googlesearch.py", line 35, in search
browser = webdriver.Firefox()
File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in init
keep_alive=True)
File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in init
self.start_session(capabilities, browser_profile)
File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
response = self.execute(Command.NEW_SESSION, parameters)
File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

```

gecko drivers is installed with version:  0.26.0
firefox version is 68.2

gecko driver log files:
```
1575459844002	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileR0L67L"
1575459844328	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1575459844329	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1575459844329	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1575459844329	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
JavaScript error: resource:///modules/sessionstore/SessionStore.jsm, line 1325: uncaught exception: 2147746065
1575459845397	Marionette	INFO	Listening on port 38539
1575459845409	Marionette	WARN	TLS certificate errors will be ignored for this session
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
1575460051084	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileHAV9Mo"
1575460051394	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1575460051394	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1575460051394	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1575460051394	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
JavaScript error: resource:///modules/sessionstore/SessionStore.jsm, line 1325: uncaught exception: 2147746065
1575460052426	Marionette	INFO	Listening on port 33021
1575460052488	Marionette	WARN	TLS certificate errors will be ignored for this session
1575460150518	Marionette	INFO	Stopped listening on port 33021
1575460177404	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileOIJDCC"
1575460177726	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1575460177726	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1575460177726	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1575460177726	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
JavaScript error: resource:///modules/sessionstore/SessionStore.jsm, line 1325: uncaught exception: 2147746065
1575460178769	Marionette	INFO	Listening on port 36967
1575460178809	Marionette	WARN	TLS certificate errors will be ignored for this session
1575460305822	Marionette	INFO	Stopped listening on port 36967
```
and the gecko driver log files in phoneinfoga folder:
```

Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by azamet.)
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by azamet.)
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by azamet.)
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by azamet.)
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by azamet.)
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by azamet.)
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by azamet.)
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by azamet.)
```

if i try to run it without sudo i get this:
```
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/home/azamet/Belgeler/cehennem/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/home/azamet/Belgeler/cehennem/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 163, in __init__
    log_path=service_log_path)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/service.py", line 44, in __init__
    log_file = open(log_path, "a+") if log_path is not None and log_path != "" else None
PermissionError: [Errno 13] Permission denied: 'geckodriver.log'
```

and again without sudo at the top i do get this error:
/home/azamet/.local/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning

**Comment by azamet90** [comment]
after fresh installing the kali same problem exist i decided to remove this tool no need to get head pain

**Comment by sundowndev** [comment]
Hi, this is a known issue of Selenium with geckodriver. If you can't get this working, consider using Docker. I'll probably work on a Chrome implementation later.

**Comment by thewasta** [comment]
Im using docker, but same error

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).
