### ISSUE TITLE
error during web search

### ISSUE THREAD

**Issue by 7h3pr0xy** [sundowndev/PhoneInfoga#181]
Would you like to use an additional format for this number ? (y/N) n
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/root/Desktop/udemy-advance/PhoneInfoga/scanners/footprints.py", line 186, in osintScan
    for result in search(req, stop=10):
  File "/root/Desktop/udemy-advance/PhoneInfoga/lib/googlesearch.py", line 49, in search
    browser = getFirefoxBrowser()
  File "/root/Desktop/udemy-advance/PhoneInfoga/lib/googlesearch.py", line 32, in getFirefoxBrowser
    return webdriver.Firefox()
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by sundowndev** [comment]
Hi, thanks for opening an issue! 👋

It seems you didn't installed geckodriver properly. Did you follow the [install instructions](https://sundowndev.github.io/PhoneInfoga/install/#install-the-geckodriver) ?

>This tool uses Firefox. So you now need to download the [geckodriver](https://github.com/mozilla/geckodriver). This driver is necessary to communicate between your installed browser and Selenium (a package used by PhoneInfoga).

You can verify Firefox and geckdriver are installed correctly by typing `which firefox` and `which geckodriver` in your terminal.

Please answer to these questions : 

1. Are you using Docker ? If no, what is your OS ? (`uname -a` for Linux/MacOS users)
2. What command did you run ?
3. Do you have the latest version of Firefox installed ?
4. Do you have the latest version of geckodriver installed ? (try `geckodriver --version`)

*Note that this tool is not tested under any version of Windows and I don't guarantee it will work properly on it.*

**Comment by itIsKappa** [comment]
It might be with the permissions for geckodriver.log
If you are in Linux, go to PhoneInfoga directory and type in this command:
chmod 666 geckodriver.log
Or in other words, change the file persmission for all users to read and write.

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).

**Comment by NICKNELSON05** [comment]
Pls help me im run this tools on termux 

Would you like to use an additional format for this number ? (y/N) n
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/PhoneInfoga/phoneinfoga.py", line 95, in <module>
    main()
  File "/data/data/com.termux/files/home/PhoneInfoga/phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "/data/data/com.termux/files/home/PhoneInfoga/phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/data/data/com.termux/files/home/PhoneInfoga/scanners/footprints.py", line 186, in osintScan
    for result in search(req, stop=10):
                  ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 49, in search
    browser = getFirefoxBrowser()
              ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 32, in getFirefoxBrowser
    return webdriver.Firefox()
           ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
