### ISSUE TITLE
please help me solve this error 

### ISSUE THREAD

**Issue by leebadcompany** [sundowndev/PhoneInfoga#182]
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/root/Desktop/PhoneInfoga/scanners/footprints.py", line 186, in osintScan
    for result in search(req, stop=10):
  File "/root/Desktop/PhoneInfoga/lib/googlesearch.py", line 46, in search
    if google_api_key and google_cx_id:
NameError: name 'google_api_key' is not defined

**Comment by sundowndev** [comment]
You didn't install the project properly. You have to create the config file https://sundowndev.github.io/PhoneInfoga/install/#create-the-config-file
