### ISSUE TITLE
Please help me!!!!!

### ISSUE THREAD

**Issue by RaAnimePe** [sundowndev/PhoneInfoga#184]
When i have installed the PhoneInfoga on my rpi 4 with raspbian and i do:
python3 phoneinfoga.py -n <phonenumber>

it gaves me error like this: 

```
Would you like to use an additional format for this number ? (y/N) n
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/home/pi/PhoneInfoga/scanners/footprints.py", line 186, in osintScan
    for result in search(req, stop=10):
  File "/home/pi/PhoneInfoga/lib/googlesearch.py", line 46, in search
    if google_api_key and google_cx_id:
NameError: name 'google_api_key' is not defined

```

**Comment by sundowndev** [comment]
You didn't install the project properly. Please [read documentation](https://sundowndev.github.io/PhoneInfoga/install/).
