### ISSUE TITLE
Can't find additional format

### ISSUE THREAD

**Issue by wajdibr** [sundowndev/PhoneInfoga#187]
Hello,
Thank you for the tool,
However running it gives me those issues:
`Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/.../PhoneInfoga/scanners/footprints.py", line 186, in osintScan
    for result in search(req, stop=10):
  File "/.../PhoneInfoga/lib/googlesearch.py", line 46, in search
    if google_api_key and google_cx_id:
NameError: name 'google_api_key' is not defined`

Grateful for any help,

Cheers

**Comment by sundowndev** [comment]
You didn't install the project properly. You have to create the config file, please [read documentation](https://sundowndev.github.io/PhoneInfoga/install/).
