### ISSUE TITLE
google_api_key is not defined

### ISSUE THREAD

**Issue by arthurdrabazha** [sundowndev/PhoneInfoga#190]
When i'm trying to search phone number via osintScan
I receives these traceback:

Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/home/arthur/PhoneInfoga/scanners/footprints.py", line 186, in osintScan
    for result in search(req, stop=10):
  File "/home/arthur/PhoneInfoga/lib/googlesearch.py", line 47, in search
    if google_api_key and google_cx_id:
NameError: name 'google_api_key' is not defined

 - OS: Linux Mint 19.3 Tricia
 - Python 3.6.9

Additional info:
MY_INPUT: python3 phoneinfoga.py -n ********** 
PWD: /home/$USER/PhoneInfoga
Exit_code: 1

**Comment by sundowndev** [comment]
You didn't install the project properly, you need to create the config file. Please [read documentation](https://sundowndev.github.io/PhoneInfoga/install/).

**Comment by arthurdrabazha** [comment]
Now I have another problem. When I do request something goes wrong.
Or maybe that's right?

file:///home/arthur/Pictures/Screenshot%20from%202020-01-13%2020-29-58.png

**Comment by sundowndev** [comment]
@arthurdrabazha It just means Google has no result for this request.

Be careful, you just leaked your location tho.

**Comment by sundowndev** [comment]
Closing due to inactivity. Feel free to reopen and add further details!
