### ISSUE TITLE
import colorama

### ISSUE THREAD

**Issue by igotyou22** [sundowndev/PhoneInfoga#193]
unable to find colorama.
Traceback (most recent call last):
  File "phoneinfoga.py", line 14, in <module>
    from lib.output import *
  File "/home/XXXXX/PhoneInfoga/lib/output.py", line 10, in <module>
    from lib.colors import *
  File "/home/XXXXXX/PhoneInfoga/lib/colors.py", line 9, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'

**Comment by igotyou22** [comment]
i went a google and looked for colorama and download it from there. it works,  I am still have a problem with from lib.args import args,parser...  args and parser is not on lib.  Thanks

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).

**Comment by novaldeng** [comment]
i need help on " python3 phoneinfoga.py -v"..thanks in advance 
 
Traceback (most recent call last):
  File "phoneinfoga.py", line 14, in <module>
    from lib.output import *
  File "/root/PhoneInfoga/lib/output.py", line 10, in <module>
    from lib.colors import*
ModuleNotFoundError: No module named 'lib.colors'
