### ISSUE TITLE
osint/reputation.json not found

### ISSUE THREAD

**Issue by butterflyx** [sundowndev/PhoneInfoga#200]
running the tool with a german number exits with an error message while searching the web.

**To Reproduce**
```
[i] Searching for documents... (limit=10)
[i] ---- Reputation footprints ----
Traceback (most recent call last):
  File "/opt/PhoneInfoga/phoneinfoga.py", line 101, in <module>
    main()
  File "/opt/PhoneInfoga/phoneinfoga.py", line 77, in main
    scanNumber(args.number)
  File "/opt/PhoneInfoga/phoneinfoga.py", line 40, in scanNumber
    osintScan(number)
  File "/opt/PhoneInfoga/scanners/footprints.py", line 202, in osintScan
    osintReputationScan()
  File "/opt/PhoneInfoga/scanners/footprints.py", line 66, in osintReputationScan
    dorks = json.load(open("osint/reputation.json"))
FileNotFoundError: [Errno 2] No such file or directory: 'osint/reputation.json'
```

file exists:
```
─[/opt/PhoneInfoga/osint]
└──╼ $ls -al
insgesamt 16
drwxr-xr-x 1 j root  156 Feb 22 16:14 .
drwxr-xr-x 1 j root  438 Feb 22 16:15 ..
-rw-r--r-- 1 j root 2241 Feb 22 16:14 disposable_num_providers.json
-rw-r--r-- 1 j root  924 Feb 22 16:14 individuals.json
-rw-r--r-- 1 j root 1307 Feb 22 16:14 reputation.json
-rw-r--r-- 1 j root  475 Feb 22 16:14 social_medias.json
```

**Desktop (please complete the following information):**
 - OS:  Linux
-  $python3 -V
Python 3.7.6

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).
