### ISSUE TITLE
I keep getting this error i updated geckodrivers too

### ISSUE THREAD

**Issue by LordA3** [sundowndev/PhoneInfoga#201]
guys im getting this error can someone help

i] Footprint reconnaissance for +9203354943923
Traceback (most recent call last):
  File "phoneinfoga.py", line 101, in <module>
    main()
  File "phoneinfoga.py", line 77, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 39, in scanNumber
    recon.scan(number)
  File "/root/PhoneInfoga/scanners/recon.py", line 104, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/root/PhoneInfoga/lib/googlesearch.py", line 49, in search
    browser = getFirefoxBrowser()
  File "/root/PhoneInfoga/lib/googlesearch.py", line 32, in getFirefoxBrowser
    return webdriver.Firefox()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'geckodriver

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).
