### ISSUE TITLE
Footprint error?

### ISSUE THREAD

**Issue by Hcrypt** [sundowndev/PhoneInfoga#203]
`Would you like to use an additional format for this number ? (y/N) n
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 101, in <module>
    main()
  File "phoneinfoga.py", line 77, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 40, in scanNumber
    osintScan(number)
  File "/root/PhoneInfoga/scanners/footprints.py", line 186, in osintScan
    for result in search(req, stop=10):
  File "/root/PhoneInfoga/lib/googlesearch.py", line 49, in search
    browser = getFirefoxBrowser()
  File "/root/PhoneInfoga/lib/googlesearch.py", line 32, in getFirefoxBrowser
    return webdriver.Firefox()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
`

Why am I getting this error?
I followed through with..

https://sundowndev.github.io/PhoneInfoga/install/

and I even installed the google-search module incase it was necessary

**Comment by edsoncudjoe** [comment]
Looks like your firefox driver has not been installed. Have you followed the instructions to install geckodriver?

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).
