### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by sinanmohd** [sundowndev/PhoneInfoga#211]
Traceback (most recent call last):
  File "phoneinfoga.py", line 101, in <module>
    main()
  File "phoneinfoga.py", line 77, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 40, in scanNumber
    osintScan(number)
  File "/home/sinan/PhoneInfoga/scanners/footprints.py", line 186, in osintScan
    for result in search(req, stop=10):
  File "/home/sinan/PhoneInfoga/lib/googlesearch.py", line 49, in search
    browser = getFirefoxBrowser()
  File "/home/sinan/PhoneInfoga/lib/googlesearch.py", line 32, in getFirefoxBrowser
    return webdriver.Firefox()
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

after running this command i got this error: python3 phoninfoga.py -n 1701*******

**Comment by sundowndev** [comment]
Hi 👋 

Please consider upgrading to [v2.0](https://github.com/sundowndev/PhoneInfoga/releases/tag/v2.0-beta) and trying to make it work. An online demo is also [available here](https://demo.phoneinfoga.crvx.fr).
