### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by VampireFox2** [sundowndev/PhoneInfoga#24]
So I've properly installed Phoneinfoga along with the requirements however when I try running it with:

`python3 phoneinfoga.py -n +1891XXXXXXX -s all --osint`

I get the following output: 

```
[!] ---- Fetching informations for +1891XXXXXXX ---- [!]
[*] Running local scan...
Traceback (most recent call last):
  File "phoneinfoga.py", line 654, in <module>
    scanNumber(args.number)
  File "phoneinfoga.py", line 602, in scanNumber
    localScan(InputNumber)
  File "phoneinfoga.py", line 268, in localScan
    'GET', 'https://restcountries.eu/rest/v2/callingcode/{}'.format(numberCountryCode.replace('+', ''))).content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

I'm not fluent in Python so I have no idea how to fix this or even understand what this means. I did everything correctly. Maybe I made a really stupid mistake and I'm just not seeing it.

**Comment by sundowndev** [comment]
Could you provide the country code of the number you tried to scan ?
It's not clear to me. +1 ?

**Comment by VampireFox2** [comment]
+1 is for the United States

**Comment by sundowndev** [comment]
Can you update the tool and retry ? It should be fixed.

**Comment by VampireFox2** [comment]
I just updated it and still had issues. It ran partially this time however it got the country code wrong. It said it was Canada when it's the US but it got the state correct which is weird. It gets to the point where it says The number is valid and possible, running Numverify.com scan.... then displays some issues. I'll copy and paste them here. 

Here it is:

$ python3 phoneinfoga.py -n +1619XXXXXXX -s all --osint
    ___ _                       _____        __                   
   / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _ 
  / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
 / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
 \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
                                                      |___/       
 PhoneInfoga Ver. v1.0.0-rc3
 Coded by Sundowndev


[!] ---- Fetching informations for 1619XXXXXXX ---- [!]
[*] Running local scan...
[*] Country code found: Canada (CA)
[+] International format: +1 619-XXX-XXXX
[+] Local format: 0619XXXXXXX
[+] Country code: +1
[+] Location: California
[+] Carrier: 
[+] Area: California
[+] Timezone: America/Los_Angeles
[*] The number is valid and possible.
[*] Running Numverify.com scan...
Traceback (most recent call last):
  File "phoneinfoga.py", line 666, in <module>
    scanNumber(args.number)
  File "phoneinfoga.py", line 625, in scanNumber
    numverifyScan()
  File "phoneinfoga.py", line 343, in numverifyScan
    data = json.loads(response.content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by sundowndev** [comment]
I was able to reproduce this. For some reasons it works fine on the release candidate branch (develop). I just merged it.

Could you retry and tell me ?

**Comment by sundowndev** [comment]
Hi, I just pushed a commit to develop branch. Could you use it to try again ?

`git checkout develop` then `git pull`

Either it will work, or you should get a custom error such as "Numverify is not available"

Thank you!

**Comment by VampireFox2** [comment]
So I ran the command you stated above and that solved it. Everything works now! The entire scan completed and I had no errors whatsoever. Thanks!

**Comment by NeOkC** [comment]
¿How can i fix this error?

[*] Running Numverify.com scan...
[!] Numverify.com is not available
[!] Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?
