### ISSUE TITLE
[Errno 8] Exec format error: 'geckodriver'

### ISSUE THREAD

**Issue by RizzoRavier** [sundowndev/PhoneInfoga#335]
Hello
Whenever I attempt to use phoneinfoga I get this error

[!] ---- Fetching informations for 10000000 ---- [!]                                         
[*] Running local scan...                       
[+] International format: +10000000       
[+] Local format: 10000000                  [+] Country found: Canada (+1)                  
[+] City/Area:                        
[+] Carrier:                                    
[+] Timezone:                  
[i] The number is valid and possible.           [*] Running Numverify.com scan...               [+] Number: (+1) 5873201274                     [+] Country:                      
[+] Location: Calgary                           
[+] Carrier:                                    
[+] Line type: landline                         
(!) This is most likely a landline, but it can still be a fixed VoIP number.                    
[*] Running OVH scan...                         
[*] Running OSINT footprint reconnaissance...   
[i] Generating scan URL on 411.com...           [+] Scan URL                            
Would you like to use an additional format for this number ? (y/N) n                            
[i] ---- Web pages footprints ----              
[i] Searching for footprints on web pages... (limit=10)                                         
Traceback (most recent call last):                File "phoneinfoga.py", line 101, in <module>      main()                                       
 File "phoneinfoga.py", line 77, in main           scanNumber(args.number)                       
File "phoneinfoga.py", line 40, in scanNumber     osintScan(number)                             File "/data/data/com.termux/files/home/PhoneInfoga/scanners/footprints.py", line 186, in osintScan                                               
 for result in search(req, stop=10):           
File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 49, in search       browser = getFirefoxBrowser()                 File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 32, in getFirefoxBrowser                                            return webdriver.Firefox()                    
File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__                 self.service.start()                          
File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start                        self.process = subprocess.Popen(cmd, env=self.env,                                           
 File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 854, in __init__         self._execute_child(args, executable, preexec_fn, close_fds,                                  File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 1700, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)                                OSError: [Errno 8] Exec format error: 'geckodriver'
$
Any help would be appreciated. Im not in any way skilled with this sort of stuff so please be descriptive.

**Comment by sundowndev** [comment]
Closing since this is related to legacy version which is no longer maintained. Consider upgrading to v2.
