### ISSUE TITLE
Help me out

### ISSUE THREAD

**Issue by PK-here** [sundowndev/PhoneInfoga#67]
When i run the command 
python3 phoneinfoga.py -n xxxxxxxxxx 
I get the error saying
Traceback (most recent call last):
  File "phoneinfoga.py", line 21, in <module>
    from scanners.footprints import osintScan
  File "/data/data/com.termux/files/home/PhoneInfoga/scanners/footprints.py", line 8, in <module>
    from urllib.parse import urlencode
ImportError: No module named parse
Help me out!

**Comment by mikediachenko** [comment]
@PK-here I do think there were some error while you were installing phoneinfoga. Try to follow the installation manual and run the app again.
