### ISSUE TITLE
I was using phone infoga when it started to check weboages it does this

### ISSUE THREAD

**Issue by hackstars101** [sundowndev/PhoneInfoga#694]
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/data/data/com.termux/files/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.9/subprocess.py", line 1817, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/PhoneInfoga/phoneinfoga.py", line 95, in <module>
    main()
  File "/data/data/com.termux/files/home/PhoneInfoga/phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "/data/data/com.termux/files/home/PhoneInfoga/phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/data/data/com.termux/files/home/PhoneInfoga/scanners/footprints.py", line 186, in osintScan
    for result in search(req, stop=10):
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 49, in search
    browser = getFirefoxBrowser()
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 32, in getFirefoxBrowser
    return webdriver.Firefox()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by hackstars101** [comment]
![Uploading Screenshot_20210216-154850_Termux.jpg…]()

**Comment by sundowndev** [comment]
You are using old version of PhoneInfoga (1.x) which is no longer supported. Please [read documentation for 2.x](https://sundowndev.github.io/PhoneInfoga/).

**Comment by Ken121992** [comment]
No pude instalarlo

**Comment by Ken121992** [comment]
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 1840, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/PhoneInfoga/phoneinfoga.py", line 95, in <module>
    main()
  File "/data/data/com.termux/files/home/PhoneInfoga/phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "/data/data/com.termux/files/home/PhoneInfoga/phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/data/data/com.termux/files/home/PhoneInfoga/scanners/footprints.py", line 186, in osintScan
    for result in search(req, stop=10):
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 49, in search
    browser = getFirefoxBrowser()
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 32, in getFirefoxBrowser
    return webdriver.Firefox()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
Eso es lo que me pone
