### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by AN0ND3C0D3R** [sundowndev/PhoneInfoga#74]
While running the command python3 phoneinfoga.py -v 

I get below issue :

Traceback (most recent call last):
  File "phoneinfoga.py", line 21, in <module>
    from scanners.footprints import osintScan
  File "/root/PhoneInfoga/scanners/footprints.py", line 12, in <module>
    from lib.googlesearch import search
  File "/root/PhoneInfoga/lib/googlesearch.py", line 14, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'

**Comment by AN0ND3C0D3R** [comment]
Should I change the Path from 2.7.16 to Python3 Version 3.7.3rc1 ?

**Comment by AN0ND3C0D3R** [comment]
Installing pip3 install config made it work ..
