### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by bosstrey85** [sundowndev/PhoneInfoga#749]
GETTING THIS ERROR MESSAGE.. HELP
Traceback (most recent call last):
  File "/root/PhoneInfoga/phoneinfoga.py", line 568, in <module>
    scanNumber(args.number)
  File "/root/PhoneInfoga/phoneinfoga.py", line 533, in scanNumber
    numverifyScan()
  File "/root/PhoneInfoga/phoneinfoga.py", line 291, in numverifyScan
    response = requests.request("GET", "https://numverify.com/php_helper_scripts/phone_api.php?secret_key={}&number={}".format(apiKey, number), data="", headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by sundowndev** [comment]
Please follow the install instructions for version 2.
