### ISSUE TITLE
Web Page FootPrints error

### ISSUE THREAD

**Issue by AN0ND3C0D3R** [sundowndev/PhoneInfoga#75]
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 89, in <module>
    main()
  File "phoneinfoga.py", line 70, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 37, in scanNumber
    osintScan(number)
  File "/root/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/root/PhoneInfoga/lib/googlesearch.py", line 22, in search
    if google_api_key and google_cx_id:
NameError: name 'google_api_key' is not defined

**Comment by sundowndev** [comment]
You didn't follow the install instructions correctly. Please read the wiki.
