### ISSUE TITLE
Cant execute the phoneinfoga file

### ISSUE THREAD

**Issue by snack0231** [sundowndev/phoneinfoga#761]
so i downloaded the zip file for phoneinfoga and i unziped it then when i try running the file it says (phoneinfoga: phoneinfoga: cannot execute binary file) Would appreciate any help.

**Comment by sundowndev** [comment]
Hi, can you provide the exact command you used and their output ? What OS/arch are you running on ?

**Comment by snack0231** [comment]
> Hi, can you provide the exact commands you typed and their output ? What OS/arch are you running on ?

I am using kali linux and i tried using (sudo bash phoneinfoga) the same way i use to launch my other programs. Im still learning how to use linux so that might be why i cant get it right.

**Comment by snack0231** [comment]
Im using kali linux and i tried using the command sudo bash because it works on my other executable programs

**Comment by sundowndev** [comment]
> > Hi, can you provide the exact commands you typed and their output ? What OS/arch are you running on ?
> 
> I am using kali linux and i tried using (sudo bash phoneinfoga) the same way i use to launch my other programs. Im still learning how to use linux so that might be why i cant get it right.

@snack0231 You don't need to use `sudo bash`. Just execute the binary : 

```shell
$ chmod +x ./phoneinfoga
$ ./phoneinfoga
```

**Comment by Mharniey** [comment]
What should I do with this
!] Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/PhoneInfoga/phoneinfoga.py", line 95, in <module>
    main()
  File "/data/data/com.termux/files/home/PhoneInfoga/phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "/data/data/com.termux/files/home/PhoneInfoga/phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/data/data/com.termux/files/home/PhoneInfoga/scanners/footprints.py", line 186, in osintScan
    for result in search(req, stop=10):
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 49, in search
    browser = getFirefoxBrowser()
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 32, in getFirefoxBrowser
    return webdriver.Firefox()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by sundowndev** [comment]
Closing due to inactivity. Feel free to reopen and add further details.
