### ISSUE TITLE
Followed instructions in wiki but getting this error

### ISSUE THREAD

**Issue by antihackme** [sundowndev/PhoneInfoga#80]
python3 phoneinfoga.py -v
Traceback (most recent call last):
  File "phoneinfoga.py", line 20, in <module>
    from scanners import localscan
  File "/home/antihack/PhoneInfoga/scanners/localscan.py", line 8, in <module>
    import phonenumbers
ModuleNotFoundError: No module named 'phonenumbers'

**Comment by sundowndev** [comment]
You didn't [installed the requirements](https://sundowndev.github.io/PhoneInfoga/install/#install-requirements).
