### ISSUE TITLE
Getting Error after installing PhoneInfoga and all the python libraries.

### ISSUE THREAD

**Issue by parteeksingh005** [sundowndev/PhoneInfoga#89]
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/opt/PhoneInfoga/lib/googlesearch.py", line 15, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'

**Comment by parteeksingh005** [comment]
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/opt/PhoneInfoga/lib/googlesearch.py", line 11, in <module>
    from urllib.parse import urlencode
ImportError: No module named parse


Now getting this error.

**Comment by RIS33** [comment]
> Traceback (most recent call last):
> File "phoneinfoga.py", line 17, in 
> from lib.googlesearch import closeBrowser
> File "/opt/PhoneInfoga/lib/googlesearch.py", line 15, in 
> from config import *
> ModuleNotFoundError: No module named 'config'

I have this problem too

**Comment by sundowndev** [comment]
Duplicate of #70

**Comment by RobinRana** [comment]
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/root/Desktop/PhoneInfoga/lib/googlesearch.py", line 15, in <module>
    from config import *
ModuleNotFoundError: No module named 'config'

i have problem help me anyone

**Comment by ashleyr889** [comment]
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/root/PhoneInfoga/lib/googlesearch.py", line 15, in <module>
    from config import *
ModuleNotFoundError: No module named 'config

Getting the same message as well... How can I fix it?

**Comment by 4NONYM4U5** [comment]
Run these commands :
sudo pip install google-search
sudo pip install config

**Comment by StyFx** [comment]
no modul named Config

**Comment by RobinRana** [comment]
Thanks i go to try

**Comment by jaderoe** [comment]
it works thanks #4NONYM4U5

**Comment by raj8887** [comment]
Traceback (most recent call last):
  File "phoneinfoga.py", line 17, in <module>
    from lib.googlesearch import closeBrowser
  File "/root/PhoneInfoga/lib/googlesearch.py", line 11, in <module>
    from urllib.parse import urlencode
ImportError: No module named parse


plz help me

**Comment by LOKESHG1234** [comment]
Traceback (most recent call last):
File "phoneinfoga.py", line 17, in
from lib.googlesearch import closeBrowser
File "/root/PhoneInfoga/lib/googlesearch.py", line 11, in
from urllib.parse import urlencode
ImportError: No module named parse
Please help me

**Comment by sundowndev** [comment]
@LOKESHG1234 Seems like you followed a tutorial to use the tool, that tutorial is not longer updated. Please read documentation.

**Comment by bonga187** [comment]
How to run phoneinfoga after installation
