### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by PsyPython** [sundowndev/PhoneInfoga#91]
I follow this installation steps https://sundowndev.github.io/PhoneInfoga/install/
on my Parrot Home 4.7 64-bit (Kernel Linux 5.1.0-parrot1-3t-amd64 x86_64)
and in the the program stops without getting much info.
I ran the follow command `python3 phoneinfoga.py -n +CCACNNNNNNNNN` where CC = Country Code; AC = Area Code and N = Phone Numbers.
Version v1.10.9.

That's the result:
Would you like to use an additional format for this number ? (y/N) 
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/home/psyparrot/Downloads/TEMP/PhoneInfoga/scanners/footprints.py", line 173, in osintScan
    for result in search(req, stop=10):
  File "/home/psyparrot/Downloads/TEMP/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

```

**Comment by sd33m** [comment]
Same issue on Win10.

**Comment by sundowndev** [comment]
See https://github.com/sundowndev/PhoneInfoga/issues/6#issuecomment-500840298

>This is an issue with geckodriver or selenium. See SeleniumHQ/selenium#3884. Make sure you have the latest version of geckodriver.

Also see [this topic](https://stackoverflow.com/questions/43713445/selenium-unable-to-find-a-matching-set-of-capabilities-despite-driver-being-in) on stackoverflow.

**Comment by sundowndev** [comment]
Do you have Firefox installed ?

**Comment by sundowndev** [comment]
Closing due to inactivity. Feel free to reopen and add further details!

**Comment by jepunband** [comment]
same. Unable to find a matching set of capabilities
