### ISSUE TITLE
How do I run through the go programming language?

### ISSUE THREAD

**Issue by ManuelQ59** [sundowndev/phoneinfoga#979]
hi, i have tried to update this new version, uh i try to run in many ways this new version of phoneinfoga v.2.4 but i have problems. can you help me, please. I think it is working through the GO programming language. I have tried the following: go run main.go, go build main.go and I get this:
***************************************************************
# github.com/sundowndev/phoneinfoga/v2/api
api / server.go: 41: 26: undefined: Assets
*****************************************************************
Hence, what else is it going on? Help me please !!!

**Comment by sundowndev** [comment]
Hi @ManuelQ59, this is an expected error since PhoneInfoga needs to build its web client first, to be able to compile. Please read [contribute documentation page](https://sundowndev.github.io/phoneinfoga/contribute/) to get started properly.

**Comment by ManuelQ59** [comment]
I HAVE TRIED IN ALL THE WAYS TO WANT TO START ACCORDING TO THE LINK YOU PROVIDED FOR ME, BUT I HAVE NOT BEEN ACHIEVING SUCCESSFULLY. THERE WILL BE SOME TUTORIAL ON HOW TO START IT PLEASE, IT WOULD BE GREATLY THANK YOU.

**Comment by ManuelQ59** [comment]
i have tried in all the ways to want to start according to the link you provided for me, but i have not been achieving successfully. there will be some tutorial on how to start it please, it would be greatly thank you.

**Comment by ManuelQ59** [comment]
@sundowndev hi, i have tried in all the ways to want to start according to the link you provided for me, but i have not been achieving successfully. there will be some tutorial on how to start it please, it would be greatly thank you.

**Comment by sundowndev** [comment]
Could you provide commands you used and the output so I can help you further on that ?

**Comment by ManuelQ59** [comment]
Hi @sundowndev, In the phoneinfoga cloned folder, I did the following:
(cd client && npm run && npm run build) And then 
cd .. 
go generate main.go
go build -v .
go run main.go

After all that procedure I did. I keep getting this:
github.com/sundowndev/phoneinfoga/v2/api
api / server.go: 41: 26: indefinide: Active

**Comment by sundowndev** [comment]
You didn't follow the instructions properly. You should run the following commands : 

```shell
(cd client && npm run && npm run build)
go generate ./...
go run main.go
```

**Comment by ManuelQ59** [comment]
Run all those commands inside the client folder?

**Comment by ManuelQ59** [comment]
when executing the following command: npm i or npm i --force, I get the following error:
*****************************************************************************************
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vue/cli-plugin-router@3.12.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-13T13_25_57_978Z-debug.log
******************************************************************************************

after that i can't run the tool as i get the same thing that started this problem.

**Comment by ManuelQ59** [comment]
┌──(root💀anony)-[/home/anony/TOOLS/phoneinfoga/client]
└─# npm run build --force
npm WARN using --force Recommended protections disabled.

> client@0.1.0 build
> vue-cli-service build

⸨⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠇ : WARN using --force Recommended protections disabled
⠋  Building for production...⸨⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠇ : WARN using --force Reco⠙  Building for production...⸨⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠇ : WARN using --force Reco ERROR  Error: Rule can only have one resource source (provided resource and test + include + exclude) in {                                               
  "enforce": "pre",
   "exclude": [
            {},
    "/home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-service/lib"
             ],
       "use": [
              {
      "loader": "/home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js",                            
      "options": {
        "extensions": [
          ".js",
          ".jsx",
          ".vue",
          ".ts",
          ".tsx"
             ],
        "cache": true,
        "cacheIdentifier": "3c5ef75e",
        "emitWarning": true,
        "emitError": false,
        "eslintPath": "/home/anony/TOOLS/phoneinfoga/client/node_modules/eslint",                                                                          
        "formatter": "undefined"
              }
              }
              ]
              }
Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
  "enforce": "pre",
  "exclude": [
    {},
    "/home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-service/lib"
  ],
  "use": [
    {
      "loader": "/home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js",
      "options": {
        "extensions": [
          ".js",
          ".jsx",
          ".vue",
          ".ts",
          ".tsx"
        ],
        "cache": true,
        "cacheIdentifier": "3c5ef75e",
        "emitWarning": true,
        "emitError": false,
        "eslintPath": "/home/anony/TOOLS/phoneinfoga/client/node_modules/eslint",
        "formatter": "undefined"
      }
    }
  ]
}
    at checkResourceSource (/home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:167:11)
    at Function.normalizeRule (/home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:198:4)
    at /home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:110:20
    at Array.map (<anonymous>)
    at Function.normalizeRules (/home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:109:17)
    at new RuleSet (/home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-service/node_modules/webpack/lib/RuleSet.js:104:24)
    at new NormalModuleFactory (/home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModuleFactory.js:115:18)
    at Compiler.createNormalModuleFactory (/home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:636:31)
    at Compiler.newCompilationParams (/home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:653:30)
    at Compiler.compile (/home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:661:23)
    at /home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:529:11)
    at /home/anony/TOOLS/phoneinfoga/client/node_modules/@vue/cli-service/node_modules/webpack/lib/Compiler.js:318:10
    at eval (eval at create (/home/anony/TOOLS/phoneinfoga/client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at run (/home/anony/TOOLS/phoneinfoga/client/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:248:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/anony/TOOLS/phoneinfoga/client/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)

**Comment by ManuelQ59** [comment]
I cloned the tool again, I went to the client folder, and I ran yarn and I get the following:

┌──(root💀tedd)-[/home/anony/TOOLS/phoneinfoga/client]
└─# yarn 
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

**Comment by ManuelQ59** [comment]
> ¿Podrías intentarlo de nuevo con hilo en su lugar? Ejecutar `yarn`para instalar dependencias en la carpeta del cliente. Gracias
> 
> ```shell
> # Ejemplo 
> (cliente de cd && hilo && construcción de hilo)
> ir a generar ./...
> ve a ejecutar main.go
> ```
> 
> `npm i` está funcionando bien en mi extremo, ¿en qué versión de nodejs está ejecutando?

┌──(root💀anony)-[/home/anony]
└─# node --version       
v16.13.2
                                                                            
┌──(root💀anony)-[/home/anony]
└─# nodejs --version
v12.22.7

**Comment by ManuelQ59** [comment]
> ```shell
> yarn build
> ```

Fixing this problem, I had to uninstall and reinstall the yarn, using this tutorial.
************************************************** ********************
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt update && sudo apt install yarn

yarn

**Comment by ManuelQ59** [comment]
> I cloned the tool again, I went to the client folder, and I ran yarn and I get the following:
> 
> ┌──(root💀tedd)-[/home/anony/TOOLS/phoneinfoga/client] └─# yarn 00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

Fixing this problem, I had to uninstall and reinstall the yarn, using this tutorial.

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt update && sudo apt install yarn

yarn

**Comment by ManuelQ59** [comment]
After executing main.go, how do I use the tool in console mode and in server mode?
******************************************************************************************************
┌──(root💀anony)-[/home/anony/TOOLS/phoneinfoga]
└─# go run main.go     
PhoneInfoga is one of the most advanced tools to scan phone numbers using only free resources.

Usage:
  phoneinfoga [command]

Examples:
phoneinfoga scan -n <number>

Available Commands:
  help        Help about any command
  scan        Scan a phone number
  serve       Serve web client
  version     Print current version of the tool

Flags:
  -h, --help   help for phoneinfoga

Use "phoneinfoga [command] --help" for more information about a command.
****************************************************************************************
I put this command and it shows me that it is not found:

┌──(root💀anony)-[/home/anony/TOOLS/phoneinfoga]
└─# phoneinfoga version    
phoneinfoga: command not found

**Comment by sundowndev** [comment]
You have to use `go run main.go` to run commands : `go run main.go version`. If you want to build the binary, use `go build`.
