### ISSUE TITLE
'geckodriver' executable needs to be in PATH

### ISSUE THREAD

**Issue by ITCMD** [sundowndev/PhoneInfoga#98]
**Describe the bug**
Infoga Crashes with many errors

**To Reproduce**
I ran the tool with the --recon parameter on a phone number.

**Expected behavior**
I expected it to come back with more results

**Full Log:**
python3 phoneinfoga.py -n "+1 111-111-1111" --recon
    ___ _                       _____        __                   
   / _ \ |__   ___  _ __   ___  \_   \_ __  / _| ___   __ _  __ _ 
  / /_)/ '_ \ / _ \| '_ \ / _ \  / /\/ '_ \| |_ / _ \ / _` |/ _` |
 / ___/| | | | (_) | | | |  __/\/ /_ | | | |  _| (_) | (_| | (_| |
 \/    |_| |_|\___/|_| |_|\___\____/ |_| |_|_|  \___/ \__, |\__,_|
                                                      |___/       
 PhoneInfoga Ver. v1.10.9
 Coded by Sundowndev

[!] ---- Fetching informations for 1111111111 ---- [!]
[*] Running local scan...
[+] International format: +1 111-111-1111
[+] Local format: 1111111111
[+] Country found: United States (+1)
[+] City/Area: San Antonio, TX
[+] Carrier: 
[+] Timezone: America/Chicago
[i] The number is valid and possible.
[*] Running Numverify.com scan...
[+] Number: (+1) 1111111111
[+] Country: United States of America (US)
[+] Location: Sanantonio
[+] Carrier: AT&T Mobility LLC
[+] Line type: mobile
(!) This is most likely a mobile number, but it can still be a VoIP number.
[*] Running OVH scan...
[*] Running custom format reconnaissance...
[i] Footprint reconnaissance for 1111111111
Traceback (most recent call last):
  File "/home/setlucas/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 37, in scanNumber
    recon.scan(number)
  File "/home/setlucas/PhoneInfoga/scanners/recon.py", line 88, in scan
    for result in search('"%s"' % (format), stop=5):
  File "/home/setlucas/PhoneInfoga/lib/googlesearch.py", line 35, in search
    browser = webdriver.Firefox()
  File "/home/setlucas/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/setlucas/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

setlucas@SetLucas-Lenovo-Z70-KDE:~/PhoneInfoga$ 

**Desktop (please complete the following information):**
 - OS: KDE Neon
 - Python 3.6.8

**Comment by sundowndev** [comment]
You did not installed geckodriver (at least properly).
